-- §A6 (Phase 12 Session 12.4b): pinned flag for user-requested queue items.
--
-- "Pinned" means: surface before priority ordering, persist through rerolls,
-- override the variety constraint, exempt from pass-over demotion.
--
-- The curiosity-box router (Phase 12 Step 4c) will reuse this same column for
-- its requests. For now, sibling queue items (generated by /generate-sibling)
-- are the only source.

ALTER TABLE queue_items ADD COLUMN IF NOT EXISTS pinned boolean NOT NULL DEFAULT false;

-- Backfill: existing sibling items that are still actionable.
-- Identified by: has a parent (sibling lineage) + non-terminal + was created
-- by user request (added_reason starts with "You asked").
UPDATE queue_items
SET pinned = true
WHERE parent_queue_item_id IS NOT NULL
  AND state NOT IN ('superseded', 'done', 'dismissed', 'bookmarked', 'skipped')
  AND added_reason LIKE 'You asked%';

COMMENT ON COLUMN queue_items.pinned IS
  'True for user-requested items (siblings, curiosity-box requests). These surface '
  'before priority ordering and persist through rerolls until engaged or dismissed.';
