-- Phase 10-rev Step 6 follow-up — cached LLM-generated edge descriptions.
--
-- The EdgePanel (skill tree, on edge click) renders a short paragraph
-- explaining WHY the two nodes are connected — what specific concepts or
-- skills from the source load-bear into the target — rather than just
-- restating the relationship type. Generated by Haiku, cached per edge_id,
-- shared across users: the first click on an edge pays for the call and
-- every subsequent viewer reads the cached row.
--
-- Mirrors the node_concept_briefs pattern (20250025). Briefs are derived
-- artefacts — the edges table stays structural, descriptions live separately
-- so they can be regenerated independently.

create table public.edge_descriptions (
  edge_id              uuid primary key references public.edges(id) on delete cascade,
  description_md       text not null,
  generated_at         timestamptz not null default now(),
  generated_by_model   text not null
);

alter table public.edge_descriptions enable row level security;
-- No end-user RLS policy: service role only (mirrors node_concept_briefs).
